spring:
  application:
    name: diary

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      timeout: 2000

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET_KEY}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          apple:
            client-name: apple
            client-id: ${APPLE_CLIENT_ID}
            client-secret: dummy
            redirect-uri: "{baseUrl}/login/oauth2/code/apple"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - name
              - email
        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?scope=name%20email&response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token

  jwt:
    secret: ${JWT_SECRET_KEY}

apple:
  url: https://appleid.apple.com
  path: key/AuthKey_{AUTH_KEY_ID}.p8
  cid: ${SERVICE_ID}
  tid: ${APPLE_TEAM_ID}
  kid: ${KEY_ID}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
      bucket-url: ${S3_BUCKET_URL}
    region:
      static: ${S3_AWS_REGION}
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    stack:
      auto: false

aes:
  key: ${AES_SECRET_KEY}
