package com.lifelog.diary.domain.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum Hobby {

    // Music
    PIANO("피아노", "Piano", HobbyCategory.MUSIC),
    GUITAR("기타", "Guitar", HobbyCategory.MUSIC),
    DRUMS("드럼", "Drums", HobbyCategory.MUSIC),
    VIOLIN("바이올린", "Violin", HobbyCategory.MUSIC),
    SINGING("노래", "Singing", HobbyCategory.MUSIC),
    COMPOSITION("작곡", "Composition", HobbyCategory.MUSIC),
    DJ("DJ", "DJ", HobbyCategory.MUSIC),
    UKULELE("우쿨렐레", "Ukulele", HobbyCategory.MUSIC),
    BASS("베이스", "Bass", HobbyCategory.MUSIC),
    FLUTE("플루트", "Flute", HobbyCategory.MUSIC),
    SAXOPHONE("색소폰", "Saxophone", HobbyCategory.MUSIC),
    CELLO("첼로", "Cello", HobbyCategory.MUSIC),
    TRUMPET("트럼펫", "Trumpet", HobbyCategory.MUSIC),
    HARP("하프", "Harp", HobbyCategory.MUSIC),
    HARMONICA("하모니카", "Harmonica", HobbyCategory.MUSIC),
    KARAOKE("노래방", "Karaoke", HobbyCategory.MUSIC),
    BAND("밴드", "Band Activity", HobbyCategory.MUSIC),
    ORCHESTRA("오케스트라", "Orchestra", HobbyCategory.MUSIC),
    RAP("랩", "Rap", HobbyCategory.MUSIC),
    HIPHOP("힙합", "Hip-hop", HobbyCategory.MUSIC),
    POP("팝", "Pop", HobbyCategory.MUSIC),
    KPOP("케이팝", "K-Pop", HobbyCategory.MUSIC),
    JPOP("제이팝", "J-Pop", HobbyCategory.MUSIC),
    CLASSICAL("성악", "Classical Singing", HobbyCategory.MUSIC),
    CHOIR("합창", "Choral Singing", HobbyCategory.MUSIC),
    JAZZ("재즈", "Jazz", HobbyCategory.MUSIC),
    ROCK("록", "Rock", HobbyCategory.MUSIC),
    BLUES("블루스", "Blues", HobbyCategory.MUSIC),
    METAL("메탈", "Metal", HobbyCategory.MUSIC),
    REGGAE("레게", "Reggae", HobbyCategory.MUSIC),
    COUNTRY("컨트리", "Country", HobbyCategory.MUSIC),
    FOLK("포크", "Folk", HobbyCategory.MUSIC),
    EDM("EDM", "EDM", HobbyCategory.MUSIC),
    RNB("R&B", "R&B", HobbyCategory.MUSIC),
    SYNTH("신스", "Synthesizer", HobbyCategory.MUSIC),
    BEATBOX("비트박스", "Beatboxing", HobbyCategory.MUSIC),
    IMPROV("즉흥", "Improvisation", HobbyCategory.MUSIC),
    PRODUCTION("제작", "Music Production", HobbyCategory.MUSIC),
    MIXING("믹싱", "Mixing", HobbyCategory.MUSIC),
    THEORY("이론", "Music Theory", HobbyCategory.MUSIC),
    LIVE("라이브", "Live Performance", HobbyCategory.MUSIC),
    RECORDCOLLECTING("레코드수집", "Record Collecting", HobbyCategory.MUSIC),
    COVER("커버", "Cover", HobbyCategory.MUSIC),
    REMIX("리믹스", "Remix", HobbyCategory.MUSIC),
    SOUNDDESIGN("사운드디자인", "Sound Design", HobbyCategory.MUSIC),

    // Entertainment
    BOARDGAMES("보드게임", "Board Games", HobbyCategory.ENTERTAINMENT),
    CARDGAMES("카드게임", "Card Games", HobbyCategory.ENTERTAINMENT),
    PUZZLE("퍼즐", "Puzzle Solving", HobbyCategory.ENTERTAINMENT),
    CHESS("체스", "Chess", HobbyCategory.ENTERTAINMENT),
    BADUK("바둑", "Baduk/Go", HobbyCategory.ENTERTAINMENT),
    SUDOKU("스도쿠", "Sudoku", HobbyCategory.ENTERTAINMENT),
    CROSSWORD("크로스워드", "Crossword", HobbyCategory.ENTERTAINMENT),
    RPG("롤플레잉", "Role-playing Games", HobbyCategory.ENTERTAINMENT),
    ESCAPEROOM("방탈출", "Escape Room", HobbyCategory.ENTERTAINMENT),
    ESPORTS("e스포츠", "E-sports", HobbyCategory.ENTERTAINMENT),
    MOBILEGAMES("모바일게임", "Mobile Games", HobbyCategory.ENTERTAINMENT),
    CONSOLEGAMING("콘솔게임", "Console Gaming", HobbyCategory.ENTERTAINMENT),
    PCGAMES("PC게임", "PC Games", HobbyCategory.ENTERTAINMENT),
    ARCADE("아케이드", "Arcade", HobbyCategory.ENTERTAINMENT),
    QUIZGAMES("퀴즈", "Quiz Games", HobbyCategory.ENTERTAINMENT),
    STRATEGYGAMES("전략", "Strategy Games", HobbyCategory.ENTERTAINMENT),
    SIMULATION("시뮬레이션", "Simulation", HobbyCategory.ENTERTAINMENT),
    MAHJONG("마작", "Mahjong", HobbyCategory.ENTERTAINMENT),
    POKER("포커", "Poker", HobbyCategory.ENTERTAINMENT),
    SPEEDCUBING("큐빙", "Speedcubing", HobbyCategory.ENTERTAINMENT),
    MOVIEWATCHING("영화", "Movie Watching", HobbyCategory.ENTERTAINMENT),
    CLASSICFILMS("명화감상", "Classic Films", HobbyCategory.ENTERTAINMENT),
    INDIEFILMS("인디영화", "Indie Films", HobbyCategory.ENTERTAINMENT),
    DOCUMENTARY("다큐", "Documentary", HobbyCategory.ENTERTAINMENT),
    FILMFESTIVAL("영화제", "Film Festival", HobbyCategory.ENTERTAINMENT),
    BINGEWATCHING("정주행", "Binge Watching", HobbyCategory.ENTERTAINMENT),
    STREAMING("스트리밍", "Streaming", HobbyCategory.ENTERTAINMENT),
    DRAMASERIES("드라마", "Drama Series", HobbyCategory.ENTERTAINMENT),
    KDRAMA("K-드라마", "K-Drama", HobbyCategory.ENTERTAINMENT),
    SITCOM("시트콤", "Sitcom", HobbyCategory.ENTERTAINMENT),
    REALITYTV("리얼리티TV", "Reality TV", HobbyCategory.ENTERTAINMENT),
    TALKSHOW("토크쇼", "Talk Show", HobbyCategory.ENTERTAINMENT),
    ANIMEWATCHING("애니메이션", "Anime", HobbyCategory.ENTERTAINMENT),
    CARTOONWATCHING("만화영화", "Cartoon", HobbyCategory.ENTERTAINMENT),
    WEBTOON("웹툰", "Webtoons", HobbyCategory.ENTERTAINMENT),
    COSPLAY("코스프레", "Cosplay", HobbyCategory.ENTERTAINMENT),
    STANDUPCOMEDY("스탠드업", "Stand-up Comedy", HobbyCategory.ENTERTAINMENT),
    COMEDY("코미디", "Comedy", HobbyCategory.ENTERTAINMENT),
    THEATERGOING("연극관람", "Theater Going", HobbyCategory.ENTERTAINMENT),
    MUSICALS("뮤지컬", "Musicals", HobbyCategory.ENTERTAINMENT),

    // Sports
    JOGGING("조깅", "Jogging", HobbyCategory.SPORTS),
    YOGA("요가", "Yoga", HobbyCategory.SPORTS),
    PILATES("필라테스", "Pilates", HobbyCategory.SPORTS),
    HIKING("등산", "Hiking", HobbyCategory.SPORTS),
    CYCLING("자전거", "Cycling", HobbyCategory.SPORTS),
    SWIMMING("수영", "Swimming", HobbyCategory.SPORTS),
    SOCCER("축구", "Soccer", HobbyCategory.SPORTS),
    BASKETBALL("농구", "Basketball", HobbyCategory.SPORTS),
    TENNIS("테니스", "Tennis", HobbyCategory.SPORTS),
    VOLLEYBALL("배구", "Volleyball", HobbyCategory.SPORTS),
    BASEBALL("야구", "Baseball", HobbyCategory.SPORTS),
    GOLF("골프", "Golf", HobbyCategory.SPORTS),
    CLIMBING("클라이밍", "Climbing", HobbyCategory.SPORTS),
    SKATEBOARDING("스케이트보드", "Skateboarding", HobbyCategory.SPORTS),
    SNOWBOARDING("스노보드", "Snowboarding", HobbyCategory.SPORTS),
    SKIING("스키", "Skiing", HobbyCategory.SPORTS),
    BOXING("복싱", "Boxing", HobbyCategory.SPORTS),
    MARTIALARTS("무술", "Martial Arts", HobbyCategory.SPORTS),
    FENCING("펜싱", "Fencing", HobbyCategory.SPORTS),
    ARCHERY("양궁", "Archery", HobbyCategory.SPORTS),
    BILLIARDS("당구", "Billiards", HobbyCategory.SPORTS),
    BOWLING("볼링", "Bowling", HobbyCategory.SPORTS),
    TAEKWONDO("태권도", "Taekwondo", HobbyCategory.SPORTS),
    DANCE("댄스", "Dance", HobbyCategory.SPORTS),
    BADMINTON("배드민턴", "Badminton", HobbyCategory.SPORTS),
    TABLETENNIS("탁구", "Table Tennis", HobbyCategory.SPORTS),
    HANDBALL("핸드볼", "Handball", HobbyCategory.SPORTS),
    ULTIMATEFRISBEE("얼티메이트", "Ultimate Frisbee", HobbyCategory.SPORTS),
    ROWING("조정", "Rowing", HobbyCategory.SPORTS),
    CANOEING("카누", "Canoeing", HobbyCategory.SPORTS),
    KAYAKING("카약", "Kayaking", HobbyCategory.SPORTS),
    PADDLEBOARDING("패들보드", "Paddleboarding", HobbyCategory.SPORTS),
    PARKOUR("파쿠르", "Parkour", HobbyCategory.SPORTS),
    SLACKLINING("슬랙라인", "Slacklining", HobbyCategory.SPORTS),
    WEIGHTLIFTING("역도", "Weightlifting", HobbyCategory.SPORTS),
    CROSSFIT("크로스핏", "Crossfit", HobbyCategory.SPORTS),
    SURFING("서핑", "Surfing", HobbyCategory.SPORTS),
    TRAMPOLINE("트램폴린", "Trampoline", HobbyCategory.SPORTS),
    SCUBADIVING("스쿠버다이빙", "Scuba Diving", HobbyCategory.SPORTS),
    EQUESTRIAN("승마", "Equestrian", HobbyCategory.SPORTS),
    WRESTLING("레슬링", "Wrestling", HobbyCategory.SPORTS),
    JUDO("유도", "Judo", HobbyCategory.SPORTS),
    KARATE("가라테", "Karate", HobbyCategory.SPORTS),
    TAICHI("태극권", "Tai Chi", HobbyCategory.SPORTS),

    // Reading Study
    NOVEL("소설", "Novel", HobbyCategory.READING_STUDY),
    ESSAY("에세이", "Essay", HobbyCategory.READING_STUDY),
    NONFICTION("논픽션", "Nonfiction", HobbyCategory.READING_STUDY),
    POETRY("시", "Poetry", HobbyCategory.READING_STUDY),
    HISTORY("역사", "History", HobbyCategory.READING_STUDY),
    PHILOSOPHY("철학", "Philosophy", HobbyCategory.READING_STUDY),
    SCIENCE("과학", "Science", HobbyCategory.READING_STUDY),
    MAGAZINE("잡지", "Magazine", HobbyCategory.READING_STUDY),
    COMIC("만화", "Comics", HobbyCategory.READING_STUDY),
    JOURNAL("학술지", "Journals", HobbyCategory.READING_STUDY),
    FLASHCARD("플래시카드", "Flashcards", HobbyCategory.READING_STUDY),
    SPEEDREADING("속독", "Speed Reading", HobbyCategory.READING_STUDY),
    AUDIOBOOK("오디오북", "Audiobook", HobbyCategory.READING_STUDY),
    CLUB("독서모임", "Reading Club", HobbyCategory.READING_STUDY),
    DISCUSSION("독서토론", "Book Discussion", HobbyCategory.READING_STUDY),
    FOREIGNLANGUAGE("외국어학습", "Language Learning", HobbyCategory.READING_STUDY),
    ONLINECOURSE("온라인강의", "Online Course", HobbyCategory.READING_STUDY),
    ANNOTATION("메모", "Annotation", HobbyCategory.READING_STUDY),
    TRANSCRIPTION("필사", "Transcription", HobbyCategory.READING_STUDY),

    // Nature, Pets
    CAT("고양이", "Cat", HobbyCategory.NATURE_PETS),
    DOG("강아지", "Dog", HobbyCategory.NATURE_PETS),
    BIRD("새", "Bird", HobbyCategory.NATURE_PETS),
    RABBIT("토끼", "Rabbit", HobbyCategory.NATURE_PETS),
    FISH("물고기", "Fish", HobbyCategory.NATURE_PETS),
    INSECT("곤충", "Insect", HobbyCategory.NATURE_PETS),
    GARDENING("정원", "Gardening", HobbyCategory.NATURE_PETS),
    PLANTGROWING("식물", "Plant Growing", HobbyCategory.NATURE_PETS),
    BONSAI("분재", "Bonsai", HobbyCategory.NATURE_PETS),
    TERRARIUM("테라리움", "Terrarium", HobbyCategory.NATURE_PETS),
    FISHKEEPING("아쿠아리움", "Aquarium Keeping", HobbyCategory.NATURE_PETS),
    BEEKEEPING("양봉", "Beekeeping", HobbyCategory.NATURE_PETS),
    MUSHROOMFORAGING("버섯채집", "Mushroom Foraging", HobbyCategory.NATURE_PETS),
    FOSSILCOLLECTION("화석채집", "Fossil Collection", HobbyCategory.NATURE_PETS),
    STARGAZING("별보기", "Stargazing", HobbyCategory.NATURE_PETS),
    CAMPING("캠핑", "Camping", HobbyCategory.NATURE_PETS),
    NATUREWALK("산책", "Nature Walking", HobbyCategory.NATURE_PETS),
    FORAGING("채집", "Foraging", HobbyCategory.NATURE_PETS),
    URBANFARMING("도시농업", "Urban Farming", HobbyCategory.NATURE_PETS),
    WILDLIFEWATCHING("야생관찰", "Wildlife Watching", HobbyCategory.NATURE_PETS),
    TREEPLANTING("나무심기", "Tree Planting", HobbyCategory.NATURE_PETS),
    FORESTBATHING("산림욕", "Forest Bathing", HobbyCategory.NATURE_PETS),
    FARM("농장", "Farm", HobbyCategory.NATURE_PETS),
    ZOOVISITING("동물원", "Zoo Visiting", HobbyCategory.NATURE_PETS),

    // Others
    DRAWING("드로잉", "Drawing", HobbyCategory.OTHER),
    PAINTING("회화", "Painting", HobbyCategory.OTHER),
    WATERCOLOR("수채화", "Watercolor", HobbyCategory.OTHER),
    OILPAINTING("유화", "Oil Painting", HobbyCategory.OTHER),
    CALLIGRAPHY("캘리그래피", "Calligraphy", HobbyCategory.OTHER),
    SCULPTURE("조각", "Sculpture", HobbyCategory.OTHER),
    KNITTING("뜨개질", "Knitting", HobbyCategory.OTHER),
    NAILART("네일아트", "Nail Art", HobbyCategory.OTHER),
    SEWING("바느질", "Sewing", HobbyCategory.OTHER),
    EMBROIDERY("자수", "Embroidery", HobbyCategory.OTHER),
    CANDLEMAKING("양초제작", "Candle Making", HobbyCategory.OTHER),
    SOAPMAKING("비누제작", "Soap Making", HobbyCategory.OTHER),
    SCRAPBOOKING("스크랩북", "Scrapbooking", HobbyCategory.OTHER),
    MODELBUILDING("모형제작", "Model Building", HobbyCategory.OTHER),
    LEGO("레고", "LEGO", HobbyCategory.OTHER),
    WOODWORKING("목공예", "Woodworking", HobbyCategory.OTHER),
    METALCRAFT("금속공예", "Metalcraft", HobbyCategory.OTHER),
    POTTERY("도예", "Pottery", HobbyCategory.OTHER),
    TRAVEL("여행", "Travel", HobbyCategory.OTHER),
    BACKPACKING("배낭여행", "Backpacking", HobbyCategory.OTHER),
    URBANEXPLORATION("도시탐험", "Urban Exploration", HobbyCategory.OTHER),
    PHOTOGRAPHY("사진촬영", "Photography", HobbyCategory.OTHER),
    FILMPHOTOGRAPHY("필름사진", "Film Photography", HobbyCategory.OTHER),
    DRONEFLYING("드론비행", "Drone Flying", HobbyCategory.OTHER),
    THREEDPRINTING("3D프린팅", "3D Printing", HobbyCategory.OTHER),
    ARDUINO("아두이노", "Arduino", HobbyCategory.OTHER),
    CODING("코딩", "Coding", HobbyCategory.OTHER),
    PROGRAMMING("프로그래밍", "Programming", HobbyCategory.OTHER),
    AI("AI", "AI", HobbyCategory.OTHER),
    ROBOTICS("로봇공학", "Robotics", HobbyCategory.OTHER),
    JOURNALING("일기쓰기", "Journaling", HobbyCategory.OTHER),
    BLOGGING("블로깅", "Blogging", HobbyCategory.OTHER),
    CREATIVEWRITING("창작", "Creative Writing", HobbyCategory.OTHER),
    POETRYWRITING("시쓰기", "Poetry Writing", HobbyCategory.OTHER),
    VOLUNTEER("봉사활동", "Volunteering", HobbyCategory.OTHER),
    LANGUAGEEXCHANGE("언어교환", "Language Exchange", HobbyCategory.OTHER),
    TRANSLATION("번역", "Translation", HobbyCategory.OTHER),
    PODCASTLISTENING("팟캐스트", "Podcast Listening", HobbyCategory.OTHER),
    MAGIC("마술", "Magic", HobbyCategory.OTHER);

    private final String koreanName;
    private final String englishName;
    private final HobbyCategory category;
}

